


const BASE_URL = 'http://localhost:3001/api/tariffs';

async function testApi() {
    console.log('🧪 Testing Tariffs API...');

    // 1. Get Categories
    try {
        const catRes = await fetch(`${BASE_URL}/categories`);
        if (catRes.status === 404) {
            console.error('❌ /api/tariffs/categories Not Found (Is server running?)');
            return;
        }
        const categories = await catRes.json();
        console.log(`✅ Categories fetched: ${categories.length}`);
    } catch (e) {
        console.error('❌ Error fetching categories:', e.message);
    }

    // 2. Create Plan
    let planId;
    try {
        const payload = {
            title: 'Test Plan Agent',
            category: 'MOVIL',
            description: 'Generated by Agent',
            price: 99.99,
            specs: { voice: 'Unlimited', data: '100GB' }
        };
        const createRes = await fetch(`${BASE_URL}/plans`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        const created = await createRes.json();
        if (createRes.ok) {
            console.log(`✅ Plan Created: ${created.name} (ID: ${created.id})`);
            planId = created.id;
        } else {
            console.error('❌ Create Plan Failed:', created);
        }
    } catch (e) {
        console.error('❌ Error creating plan:', e.message);
    }

    // 3. Delete Plan
    if (planId) {
        try {
            const delRes = await fetch(`${BASE_URL}/plans/${planId}`, { method: 'DELETE' });
            if (delRes.ok) {
                console.log('✅ Plan Deleted (Cleanup)');
            } else {
                console.error('❌ Delete Plan Failed');
            }
        } catch (e) { console.error('Error deleting:', e.message); }
    }
}

testApi();
