name: momvision-cms
services:
- name: web
  source_dir: /
  github:
    repo: Gabrielspr25/crm-system
    branch: main
  build_command: |
    cd server && npm install
    cd ../client && npm install && npm run build
  run_command: cd server && npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: JWT_SECRET
    value: "momvision_jwt_secret_2024_secure_key_production"
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
  - key: FRONTEND_URL
    value: "${APP_URL}"

- name: client
  source_dir: /client
  github:
    repo: Gabrielspr25/crm-system
    branch: main
  build_command: npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  - path: /admin
  - path: /login

databases:
- name: momvision-db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database
  version: "13"

alerts:
- rule: CPU_UTILIZATION
  value: 85
- rule: MEM_UTILIZATION  
  value: 85
- rule: RESTART_COUNT
  value: 5